### ISSUE TITLE
Empty handed attacks do no damage

### ISSUE THREAD

**Issue by poisongod** [wendall911/TinkerSurvival#100]
Tinker Survival is an excellent mods, but it doesn't make sense to attack empty-handed with no damage, what do I need to do so that I can also take damage empty-handed

**Comment by wendall911** [comment]
I think it makes sense. Punching zombies and trees is silly. There is a config option for this. Please check the config. GENERIC_DAMAGE. Just set to what you think the damage should be.

**Comment by poisongod** [comment]
Okay, thank you.
