### ISSUE TITLE
Tinkers add-ons that add more weapons do no damage 1.18.2 

### ISSUE THREAD

**Issue by FullMetalMaster** [wendall911/TinkerSurvival#103]
![image](https://github.com/wendall911/TinkerSurvival/assets/52523300/57351c47-812a-4335-a114-80c483ed2b0a)
![image](https://github.com/wendall911/TinkerSurvival/assets/52523300/e7cc6128-c9f2-4c1d-95de-92f53ef20bf4)
these are the corresponding mods that are affected currently with the latest version of Tinker survival add-on weapon mods do not do any damage? hopping a patch can fix this

**Comment by wendall911** [comment]
This is configurable. Just have to add the mods to the configuration. Most of these mods fall way behind on updates, so I don't add them to the default configuration.
