### ISSUE TITLE
Saw Dupe Bug

### ISSUE THREAD

**Issue by Ryno1278** [wendall911/TinkerSurvival#108]
When using repair kits on the saw you use to craft planks from logs, the repair kit will be used but not the original damaged saw, thus a new duplicate saw will be crafted allowing the player to make infinite copies of the saw.

Suspected reason:

I think what causes this is that the saw item is set to stay in crafting grid when crafted because it is used in crafting recipes, so when you craft the saw with a repair kit the damaged saw stays and the new repaired saw is outputted, this duplicates the saw. Since other tinkers tools aren't used in crafting recipes repair kits work fine, its just the saws.

Fix:
I am definitely not experienced enough in java to know how to fix this so I hope you can figure this one out, as its a fairly annoying bug.

Thank you 
-Ryno

**Comment by wendall911** [comment]
Oh, yeah, this is because Tinkers'  has a million duping bugs. I have worked around this in 1.18.2, but they may have "fixed" it, again breaking my duping fix. Is this for the 1.19.2 or the 1.18.2 version?

**Comment by wendall911** [comment]
Fix is up on Curseforge and Modrinth. Thanks for the report!
