### ISSUE TITLE
[1.19.2] Crash with patchouli wanting chargedcharms classes

### ISSUE THREAD

**Issue by YOYOK9** [wendall911/TinkerSurvival#109]
With the newest versions of tinker survival the game will crash with patchouli installed, logs show it asking for chargecharms classes. Adding the mod fixes the issue. 

I tested:
- Tinker Survival and needed dependency mods in their own profile - Worked
- Patchouli on its own - Worked
- TCon + Survivalist Essentials + Patchouli together - Worked
- All 5 mods together - Failed

Logs with error: https://gist.github.com/YOYOK9/b1078597a20fff7cd07e46166a2b77b8

Also tired the same mod set with different versions of Tinker Survival
- Versions: 4.1.1.5, 4.1.1.4, 4.1.1.3 - Failed 
- Version 4.1.1.2 - Worked

Mods used:
Forge: 43.3.13
Mantle: 1.19.2-1.10.36
Patchouli: 1.19.2-77
Survivalist Essentials: 1.19.2-4.2.0.15
Tinkers Construct: 1.19.2-3.8.3.39
Tinkers Survival: 1.19.2-4.1.1.5 (version in log)

**Comment by wendall911** [comment]
Oh, damn. My bad. That is caused by a book entry in the modpack book (for the official modpack) I will get a fix out for this tomorrow. In the meanwhile, you can install charged charms and it will fix the issue. https://www.curseforge.com/minecraft/mc-mods/charged-charms

**Comment by wendall911** [comment]
Ok, release for 1.19.2-4.1.1.6 is up on curseforge and modrinth. Thanks for reporting!
