### ISSUE TITLE
Child Laughter???

### ISSUE THREAD

**Issue by NielsPilgaard** [wendall911/TinkerSurvival#11]
What in gods name is up with the child laughter that plays whenever attempting to break a block without the right tool? It's going to haunt my dreams for a while...

**Comment by wendall911** [comment]
Minecraft started life as a zombie apocalypse survival game. It has turned into basically animal crossing. The purpose of this mod is to take back some of the survival aspect (fun) of the game. The sounds are for fun and to give a clear indication that expecting to break stuff without a tool is silly.

**Comment by NielsPilgaard** [comment]
I see. Would you consider making a config to disable it? It really breaks immersion, for me atleast.

**Comment by NielsPilgaard** [comment]
I'm guessing the lack of response means no?
