### ISSUE TITLE
Repairing Saws causes duplication

### ISSUE THREAD

**Issue by zerafox** [wendall911/TinkerSurvival#110]
When repairing a Saw at a Tinker Station it seems to duplicate itself.
1.19.2-4.1.1.6

The saw I'm seeing this on (because I haven't gotten higher tier yet) is stone, I placed a damaged saw into the Station, withdraw the repaired version on the right-side and close the station. A "ghost" saw is hidden there however, attempting to add a new tool or just simply click it to remove it.

This seems to occur without fail and only with a Saw.
Any other tool or weapon has yet to replicate this behavior at all.

**Comment by wendall911** [comment]
Make sure you update to the latest version, as there is a fix for this
already.

**Comment by zerafox** [comment]
And which version would that be because I am on the latest version available already. >.>
1.19.2-4.1.1.6 says it is the latest release and that is what I'm running.

Just as I'm already running SurvivalistEssentials 1.19.2-4.2.0.15
So if there's an update beyond those, Cureforge isn't showing it.

Unless you're talking about versions higher than 1.19.2, which is where Tinker's Construct stops at. It doesn't go higher than 1.19.2 which is why I'm on that version running Tinkers and your addons for it.
I use the CurseForge app for managing my mods/modpacks, confirming everything is up to date prior to launching the game itself. There is nothing more for me to update to.

**Comment by wendall911** [comment]
Oh, I see it now. This is a TConstruct bug I fixed long ago, but is now back again. I"ll get a fix out soon and let you know.

**Comment by wendall911** [comment]
Ok, update to the latest, it will fix this issue. I will make sure to test this better in the future, as this is a recurring bug in Tinkers' Construct.

**Comment by zerafox** [comment]
> Ok, update to the latest, it will fix this issue. I will make sure to test this better in the future, as this is a recurring bug in Tinkers' Construct.

I don't have the problem with original Tinker's items doing this, it's only the Saw.
But I will update to those builds, thank you!

**Comment by wendall911** [comment]
It is because the saw is a crafting item. They don't check to see if the tool is a crafting item for the repair kit recipes, so it duplicates. Creating dupes has been a problem in TCon forever. This is because of non-standard stuff in crafting. It is easy to fix, but I haven't sent a patch, given there is a backlog of Pull Request and it doesn't look like the one person doing all the coding accepts outside contributions. And since I'm not a bro-coder on Discord all day, I just ignore it and apply a fix locally.
