### ISSUE TITLE
Can't harvest slime vines

### ISSUE THREAD

**Issue by multihorse** [wendall911/TinkerSurvival#113]
Neither the hoe, kama, shears, knife, nor any other tool is capable of harvesting slimy vines to craft tools with. Slimy vines is one of the best bowstring choices, especially for later in the game. This is a major oversight resulting from the Tinker's Survival tool barrier integrations.

**Comment by wendall911** [comment]
@multihorse update Survivalist Essentials to the latest and everything will work. I didn't have the vines (or leaves) tagged so they harvest normally. Survivalist Essentials has been updated so this is resolved.
