### ISSUE TITLE
Request: Block Blacklist

### ISSUE THREAD

**Issue by NielsPilgaard** [wendall911/TinkerSurvival#12]
Hey!

I was wondering if you would consider making a config for allowing the harvest of specific blocks without the correct tool?
Context: I'm using the mod "Simple Camp Fire", which adds in Campfires that burn up after some time, leaving behind an "Ash Residue" block. The problem is, that block needs to be removed with a Shovel because of Tinkers' Survival, but the intuitive thing (for me atleast) is to remove it by-hand.

**Comment by wendall911** [comment]
That is an issue with the author of the other mod. Really, it is my intention to go with the required tool and not micro-manage everything. There are some mods around that allow re-configuring harvestability of individual blocks. I think Tinkered Hegemony, among others allow you to do this.

**Comment by NielsPilgaard** [comment]
Fair enough, thanks for the quick answer.
