### ISSUE TITLE
Bed Use Cooldown

### ISSUE THREAD

**Issue by VinterNacht** [wendall911/TinkerSurvival#14]
Rather than making it so that you can't go to sleep, provide a third option.

Upon placing a bed it begins a configurable cooldown timer (Default 20 RL Minutes) before it can be used as a place to sleep by ANYONE.

If you're switching spawnpoints to a pre-existing (or post cool-down) bed, you get a configurable cooldown timer before you can switch beds again. (Default 140 minutes, or 1 MC Week).

This way beds can still be as a way to sleep the night away, but you can't just carry them around with you to pass the night whenever you please.

I know a lot of people will find the 140 minute cooldown too high, so maybe default it 20 minutes (One MC Day) as well.

**Comment by wendall911** [comment]
I think this is an interesting idea. We ended up fixing this mechanic through changing the day/night cycle. I'll provide more details soon on this to give an idea of how we addressed it in our mod pack. I think this is a good candidate to add to the game.

**Comment by JadianRadiator** [comment]
I concur with this suggestion.
I need to allow players of my pack to sleep the night away, so I don't want to use this mod.
But this mod does the early-game progression absolutely perfectly for my pack, so I can't switch to a different mod.

**Comment by wendall911** [comment]
Hi, I will get a release out for this with the ability to override this mechanic. I'll give details on how we modified the day/night cycle as well. Thanks for this, I'll comment here when it is released.
