### ISSUE TITLE
Better Insulation and Chilling for Construct Armor

### ISSUE THREAD

**Issue by Guinaro** [wendall911/TinkerSurvival#17]
Currently your Construct Armory Insulated Wool Armor or Chilled Slime Leggings do not suffice to survive in a Serene Seasons, TAN & B3M Time Speed Mod enhanced game.
Even when fully clothed (4pieces) in winter time without standing next to lava I'm suffering from hypothermia within minutes, making playing in winter time an impossibility. Especially when winter can last 180+ realtime hours.

It seems that adding one or several insulating piece to your armor give you a single level trait of Insulated. I hope you would reconsider this making your traits multilevel, so that each piece in construction of your armor allows for increasing your insulation/chilling levels and temperature altering items.
Furthermore I would hope that making your traits conflicting with eachother, thus either you have Chilled Armor or Insulated Armor, but not both!

Lastly I hope you would also add MultiLevel Modifiers: Insulation Plate and Chilling Plate so that we can use these to add Insulation or Chilling to other Construct Armory Armors and making those also useful, otherwise in TAN environment you are condemned to always use your Wool/Chilling Armor.
I would expect that you need to start out in Wool or Chilled Slime Armor, but that when you are able to produce Heating and Cooling Coils you could use those to create Insulation or Chilling Plates to create other types of armor which can withstand a TAN environment.

Guinaro

**Comment by wendall911** [comment]
I totally agree with you here. I'll do a very long response to this and explain how we modified our modpack to deal with this issue. The very short version is that those mods are poorly balanced. We just tried to match what the slime and wool armor do, which isn't good enough with the default setting. I will get back to this soon and give a proper response.
