### ISSUE TITLE
Configuration for rock gen.

### ISSUE THREAD

**Issue by SynexWolf** [wendall911/TinkerSurvival#18]
I have found out that rocks aren't generation on dried sand in the wasteland biome in BOP. Is there any chances that you could add a config to allow rocks to gen in certain biomes or on certain blocks?

**Comment by wendall911** [comment]
I don't have a config for this. I think this would be a great thing to add though. Expect this in the next release. May be a few weeks out, but will happen.

**Comment by wendall911** [comment]
I wasn't able to add a config, but I did make sure that rocks generate in biomes with that type of ground covering. It is a lot more work to do a per-biome list, as I'm not sure exactly how that would look given the sheer number of biomes.
