### ISSUE TITLE
zh_cn.lang

### ISSUE THREAD

**Issue by SpiritSb2O3** [wendall911/TinkerSurvival#19]
Hi,im a chinese player(my english is pool).I really like your work,this mod is really cool.I made a lang,for reference only.

[zh_cn.txt](https://github.com/wendall911/TinkerSurvival/files/2386283/zh_cn.txt)

**Comment by wendall911** [comment]
Thank you for the contribution! I'll have this reviewed and added in the next release.

**Comment by wendall911** [comment]
@SpiritSb2O3 I added this translation in #29 if you have time, there are a few additional items added that need translation.

**Comment by ChromaPIE** [comment]
Sorry for noticing it after this quite a long time but, me and my friends, both native Chinese speakers, found the localization file uploaded above contains some lines in which the words are quite offensive or nonsensically quoting some unendurable memes. If you are still actively maintaining this mod we would love to make a fixed version of it for you to get it updated. It's okay if you're not planning to make updates of this mod, we have our own way to take the zh_cn localization project over, using [i18n Update Mod](https://minecraft.curseforge.com/projects/i18nupdate).

Hoping for your reply.

**Comment by wendall911** [comment]
@ChromaPIE Thank you for pointing this out. I should have had one of my Chinese speaking friends read this. Can you provide an updated file?

**Comment by ChromaPIE** [comment]
Here is the fixed one, also by SpiritSb2O3. We've made contact with him and knew that he made the first localization with loose thinking and this one is the editted one he made a few days after that but he forgot to upload it here for some reasons. The content of the new one has been verified. 

[zh_cn.lang.zip](https://github.com/wendall911/TinkerSurvival/files/5375660/zh_cn.lang.zip)

**Comment by deshark42** [comment]
> Here is the fixed one, also by SpiritSb2O3. We've made contact with him and knew that he made the first localization with loose thinking and this one is the editted one he made a few days after that but he forgot to upload it here for some reasons. The content of the new one has been verified.

为什么该翻译文件现在i18n仍未收录？
