### ISSUE TITLE
Deplete hunger/saturation and thirst if sleeping is enabled

### ISSUE THREAD

**Issue by Dragnier** [wendall911/TinkerSurvival#2]
This is the one thing I see that needs to be an actual option, on or off. Not allowing sleep without including an option to turn that off is liable to severely decrease the usage of your mod.

If you aren't willing to allow an option setting for no sleep; what about having sleep deplete your hunger/saturation to 3 haunches each instead? This would be more survivalist by requiring people to eat after sleeping and maintain some form of food production as a result.

**Comment by Rikshy** [comment]
It is in the config - default true
`        # I cry myself to sleep at night...
        B:NO_SLEEPING=true`

**Comment by wendall911** [comment]
I'll add a note in the wiki that it is configurable. I like the hunger debuff idea. You can access the config via the mods option in the loading screen, or edit config/tinkersurvival.cfg

**Comment by Dragnier** [comment]
@wendall911 Ah, yeah... I didn't actually load the mod to check the config because there was no mention of it being configurable in the wiki. Thanks for adding that little note. Also, I'm glad you like the hunger debuff idea and I hope to see it as an option.

**Comment by wendall911** [comment]
@Dragnier Reopening this as an enhancement so you'll be notified when I add this. Thanks for the suggestion.

**Comment by VinterNacht** [comment]
Of course, if you're going to have hunger/thirst deplete while sleeping, you should also have healing happen while sleeping.
