### ISSUE TITLE
[Suggestion] Better with Mods & Monk Mod Compat.

### ISSUE THREAD

**Issue by Keetarin** [wendall911/TinkerSurvival#20]
Love the mod, though with my personal pack, being able to "punch" wood and stone for the monk mod would be nice. I honestly think a good way to implement compat with monk mod would be to make the player take damage from punching things that they can't mine barehanded yet.

It would also be useful for BWM since you "could" mine a tree barehanded but would get reduced stuff in addition to the pain.

Compat with monk mod & BWM please?

**Comment by Darkehart** [comment]
To expand on this, could we get a whitelist for punchable objects? I would like to be able to punch Immersivecraft rocks and stick piles in order to pick them up. ^.^

**Comment by wendall911** [comment]
I'm not sure how this integration will work. I need to investigate. One super annoying thing about Minecraft, and what this mod tries to address is that you shouldn't be able to punch down trees. Of course, monk  mod might be a case for this.

What is BWM mod?

**Comment by Keetarin** [comment]
BWM is Better known as Better With Mods.
