### ISSUE TITLE
Player hand is also affected by vanilla tools

### ISSUE THREAD

**Issue by OrderlyUnicode** [wendall911/TinkerSurvival#21]
I understand why you might want to leave it like that, but in my particular case, as the author of a pack that already has a mod that renders vanilla tools useless by proxy (Better With Mods kind of at least makes stone and wood tools useless, and you can't really skip those stages without Tinkers') I see no need in leaving a player defenseless if they happened to get a bad spawn and aggro'd something before they made any tools.

I would be willing to settle for a config option.

**Comment by O13SC3N3** [comment]
You can beat everything to death with the rocks you pick up. There will always be a way. And nothing stops you from blacklisting items via config, or using crafttweaker.

**Comment by OrderlyUnicode** [comment]
I wasn't aware that you could do this with rocks. I would still like the ability to blacklist player hand, if that's possible.

**Comment by O13SC3N3** [comment]
I can agree with you, only reason I found that out was because developing my modpack I got over ran and it was the only thing in my hand it did 1-2 damage... but still it was better then nothing lol
