### ISSUE TITLE
Tweak Recipes with Craft Tweaker not working

### ISSUE THREAD

**Issue by IsakViste** [wendall911/TinkerSurvival#23]
Hi
I'm trying to remove a recipe from Tinker Survival using Craft Tweaker to add my own and can't get it to work, the CT log says that the recipe has been removed, however I can still use that recipe in-game.

**Recipes.zs**
```
recipes.removeByRecipeName("tinkersurvival:string");
recipes.addShaped("wool_to_string", <minecraft:string> * 2, [[<ore:ticKnife>.transformDamage()], [<ore:blockWool>]]);
```

**CT Log**
`[POSTINITIALIZATION][CLIENT][INFO] Removing recipe with name "tinkersurvival:string"`

**[Ingame Screenshot](https://imgur.com/a/qnXwCRY)**
As can be seen, my new recipe has been successfully registered, but the old recipe is still there...

I have asked over at CT's discord, and they believe that this is an issue from this mod, and not CT: apparently could have something to do with [recipes being updated in the postinit](https://github.com/wendall911/TinkerSurvival/blob/a4f4e0a78d913b9ddc90f258a93f3f78bf40cf9a/src/main/java/tinkersurvival/proxy/CommonProxy.java#L93) and that the recipes are getting registered after CT attempt to remove them.

**Comment by wendall911** [comment]
I'm not sure what you're trying to achieve here. The mod has a very limited number of items that are required for the mod to function. Yes, this is updated in postinit, and will stay there because of the functionality the mod provides. Care to elaborate?

**Comment by IsakViste** [comment]
I do realise this. However in my situation, some of these recipes are not well enough balanced with how I've configured my other mods, so I wished to remove the recipes, and remake them:
Ex: I want 4 sticks from a plank when using a TiC Saw instead of 2
These are just small changes for my personal gameplay style and that's why I don't mind using CraftTweaker to manually do all of this, however this causes problems (for me) when CT does not manage to remove recipes from your mod...

From what I've understood, if possible, you should initialise recipes in init and not in postinit (when possible):
[Same issue they had for the Railcraft mod](https://github.com/Railcraft/Railcraft/issues/1610#issuecomment-470337877)

**Comment by wendall911** [comment]
Ok, I'll see if it can be moved to init. The issue I'm having is that your request doesn't make any sense. The purpose of the mod is to provide some early game progression. Doubling output defeats the purpose honestly. The intention here is to extend the early gameplay, not reduce it. If that is your thing, this probably isn't the mod you're looking for.

**Comment by wendall911** [comment]
Looking at the code, the reason is that there is a lot of postInit setup for integration with other mods wood products. It isn't possible to do this in init. I think the best thing to do here is provide a config option for this.

**Comment by wendall911** [comment]
@IsakViste Please let me know everything that there should be a configuration value for. The only way this mod can work is to do this in postInit. I think there is some hope in 1.13 to do this in init.

**Comment by IsakViste** [comment]
I see your point, and I'm sorry for the bother!

The thing is this mods provides some features that I love (knife, hatchet, saw, rock piles, ...), and I have other mods for early progression that fit well with this (example: Geolosys for slower rate getting minerals), and so I want to optimize certain recipes, and some of them are from this mod. I realise this can be seen as nitpicking, but I feel it's important to have the ability/opportunity to customise.

Personally I don't mind a boolean to just disable/enable all recipes, and I make sure myself to make one for each (do put a warning for other users though so you don't get flooded with "bug reports" if they 'accidentally' disable all recipes), otherwise if too much work, I currently wish for tinkersurvival:string and all the tinkersurvival:stick (1 to 1xx) to be configurable.

Again sorry for the weird request, thanks for looking into it! 👍

**Comment by wendall911** [comment]
@IsakViste Looking at this now. So for game balance, the crude saw gives 2 sticks, and the TiC saw gives 4 sticks. I can make this configurable, but it appears as though it is already set to what you are looking for.

**Comment by wendall911** [comment]
We added a bunch of configuration options for the next release. Please let me know if you have any other requests.
