### ISSUE TITLE
Config for Stick Drops

### ISSUE THREAD

**Issue by kandivia** [wendall911/TinkerSurvival#32]
Can we get a config to disable sticks dropping from leaves? I'm looking to use Twigs from BasketCase instead. Thanks.

**Comment by wendall911** [comment]
Sure, will add to the next release. Makes sense.

**Comment by wendall911** [comment]
@kandivia I added config options for stick drop rate. You can set values to 0.0F for values if you don't want sticks to drop (in the Balance section):
STICK_DROP_CHANCE_HAND
STICK_DROP_CHANCE_KNIFE
