### ISSUE TITLE
Add support to underground biome.

### ISSUE THREAD

**Issue by Mrthomas20121** [wendall911/TinkerSurvival#33]
underground biomes replace minecraft stone with new stones, gravel with new gravels, and sand with new sands(you can still find vanilla stone, sand and gravel but it's rare).

because it replace vanilla gravel you cannot get flint and thus, cannot make crude tools.

suggestion: make so that underground biome cobble is dropped when you break a rock pile(cobble need to be the same as  the underground stone, so just like in TFC).

**Comment by ghost** [comment]
Underground Biomes Constructs has the same issue. I can't harvest gravel to get flint. Are you using the oreDict gravel? #34 should resolve the immediate issue, but others could emerge for a number of mods without full oreDict.

**Comment by VinterNacht** [comment]
Seriously having an issue with this as well.

**Comment by wendall911** [comment]
This is changed in 1.18.+ Appreciate the feedback.
