### ISSUE TITLE
Integration support for Iguana Tweaks Reborn fint drop.

### ISSUE THREAD

**Issue by wendall911** [wendall911/TinkerSurvival#36]
do you think there could be a way to work the flint shards around iguana tweaks reborn flint drop change so I can use the mods with each other cooperatively?

**Comment by wendall911** [comment]
I looked at the mod, but I don't see what you are talking about. Do you mean the flint shards in Tinkers' Construct? If so, that doesn't make sense, because the shards are only used for making crude tools.

**Comment by Insane96** [comment]
Iguana Tweaks Reborn changes nothing about Flint nor Gravel
