### ISSUE TITLE
Sapling to Stick only works with Oak Sapling

### ISSUE THREAD

**Issue by Dragnier** [wendall911/TinkerSurvival#4]
Tried to use a knife to make sticks from saplings but it only works with the oak sapling.

**Comment by wendall911** [comment]
I fixed this in the build I just pushed! I was going to make a separate issue, but ended up fixing this in #3

**Comment by wendall911** [comment]
Thanks again @Dragnier keep the issues coming. I discovered the sapling issue last night as well. I was just lazy and lumped it into the plank recipe fix.
