### ISSUE TITLE
[Suggestion] Change how vanilla item nerfing works

### ISSUE THREAD

**Issue by ghost** [wendall911/TinkerSurvival#41]
I'd like to leave a suggestion for what I think would be a better way of nerfing vanilla tools. Currently, the way that this mod goes about this is by making vanilla tools (and armor if ConArm is installed) completely unusable.
While this does work, it feels like a rather arbitrary restriction. I think a better method for nerfing vanilla items would be to give them extremely low durability, instead of disabling them completely. Vanilla items would break after a few uses or even instantly. This would make the restrictions that this mod imposes on gameplay feel much more natural, and it would make more sense.

**Comment by wendall911** [comment]
Thanks for the suggestion, but this is an immersion mod, not a bolt onto vanilla mod. There are other mods that would better suit this kind of need.
