### ISSUE TITLE
[Suggestion] Ability to disable block breaking mechanics entirely

### ISSUE THREAD

**Issue by UnlimatedStone9** [wendall911/TinkerSurvival#43]
To put it simply, I would like the ability to disable the block breaking mechanics entirely.
A single config, so I don't have to keep adding multiple mods ID's to the configs to disable the mechanics, and so players can still punch blocks like logs with their fists again.

**Comment by JadianRadiator** [comment]
I didn't know you could disable the block breaking mechanics for the mods you specify.
How the heck do I do that?
Because the option in the default config files only applies to the tools and armor,
and not breaking the blocks themselves.

**Comment by wendall911** [comment]
Honestly the mod is pretty useless without the breaking mechanics. It is intended to be an immersion mod. I recently added MOD_BLOCKS_WHITELIST to address this for some decorative mods.
