### ISSUE TITLE
对于匠魂生存无法兼容碎矿锤的问题

### ISSUE THREAD

**Issue by VillagerGold** [wendall911/TinkerSurvival#48]
作者好，我在制作自己的作品时发现Tinkers' Survivalmod存在问题，Tinkers Complementmod会和Ex Nihilo: Creatiomod联动，而Tinkers Complementmod的碎矿锤无法破坏圆石一类的方块，且不能通过白名单解决，希望作者能对此进行更新，谢谢

**Comment by jiuyaolx** [comment]
大哥，讲英文啊，作者不会中文啊
Hello, I found that Tinkers' Survival has problems when making my modpack. Tinkers Complement will link with Ex Nihilo: Creatiomod and Tinkers Complement Sledge Hammer cannot destroy blocks such as cobblestone, and cannot be solved by whitelisting. I hope the author can update this, thank you
other, the Fixes #35 is no work, only useful in the first few seconds of entering the game save, ic2 wrench still does not recognize
The above is from Google Translate

**Comment by wendall911** [comment]
I recently fixed ic2 issues with the latest version. Not sure if it will work for Ex Nihilo.
