### ISSUE TITLE
[Suggestion] Make a whitelist config to whitelist blocks to be breakable via fist

### ISSUE THREAD

**Issue by JadianRadiator** [wendall911/TinkerSurvival#49]
I want me and my modpack's players to be able to pickup specific blocks with an empty fist.
As it currently stands you have to use an axe to pickup Tinker's Construct's tables/stations.
Edit:
I am assuming that you can't add an empty fist to the tool whitelist.
If I'm wrong, do I just enter "minecraft:air" as the tool?
Edit2:
adding "minecraft:air" did not work

**Comment by trollkind** [comment]
Yes please. I'm using the Travelers Backpack mod and unfortunately you can only break a placed backpack (which counts as a block) with your hand but Tinkers Survival disallows that. I whitelisted the mod in tools and armor but it is neither and doesn't change anything. Works fine when I load the save without tinkersurvival.

**Comment by wendall911** [comment]
I added this in the latest release for 1.12 for mods like the backpack one. It is called MOD_BLOCKS_WHITELIST in the blocks section.
