### ISSUE TITLE
Dynamic Trees support

### ISSUE THREAD

**Issue by juraj-hrivnak** [wendall911/TinkerSurvival#51]
### The Issue
Tinker's Saws cant break any Dynamic Trees logs and branches.

**Comment by JadianRadiator** [comment]
Tinker's Saws are not axes.
You're looking for Tinker's Hatchet, Mattock or Lumber Axe.

**Comment by juraj-hrivnak** [comment]
Hmm, interesting! I thought you can chop down a tree with a saw, but no problem with that.
I'm closing this.
