### ISSUE TITLE
Can't craft crude axe

### ISSUE THREAD

**Issue by KyroDragonBane** [wendall911/TinkerSurvival#53]
I made a modpack and i put this in it. I played with it before but i can't craft the crude axe in this modpack for some reason. And I don't know where the conflict is coming from. The axe also doesn't appear in the JEI.
![Screenshot (1)](https://user-images.githubusercontent.com/80913330/111665482-b2751480-880a-11eb-84fa-f9db59f8a955.png)
![Screenshot (2)](https://user-images.githubusercontent.com/80913330/111665487-b3a64180-880a-11eb-9eb8-5866a7364bba.png)
![Screenshot (4)](https://user-images.githubusercontent.com/80913330/111665495-b43ed800-880a-11eb-9f9b-ac3daae97ef6.png)
![Screenshot (5)](https://user-images.githubusercontent.com/80913330/111665497-b4d76e80-880a-11eb-8cd2-a773d9090e01.png)

**Comment by wendall911** [comment]
I think TinkeredHegemony disables all tools. There might be a way to override that in the configuration.

**Comment by KyroDragonBane** [comment]
> I think TinkeredHegemony disables all tools. There might be a way to override that in the configuration.

That was it thanks a lot. I know it was stupid of me not to realize.
