### ISSUE TITLE
Whitelisting Mod tools can be a pain, and sometimes doesnt work (1.12.2)

### ISSUE THREAD

**Issue by Wubadubb** [wendall911/TinkerSurvival#56]
To be completely honest, this mod could use some info on how to properly whitelist mods for things like their tools and armor sets. What I do Is I type in the name of the mod, so:
examplemod-1.12.2.jar
I'd type
examplemod
into the box for whitelisting.
Am I doing this wrong?

**Comment by ACGaming** [comment]
Kind of, you‘d want the mod ID, not the archive base name.
Open up the respective mod jar file with an archive tool of your choice and open the `mcmod.info` file with an editor. Check for the value of `modid`, this is what should go in your Tinkers‘ Survival config.

**Comment by wendall911** [comment]
@Wubadubb You can enable advanced tooltips in game with F3+H and just look at any item from that mod. The format is modid:item_name, you'll want the modid. The name of the jar file is often times random. It is also different from the id on curseforge, so looking at an item is the best bet.
