### ISSUE TITLE
Unable to obtain flint shards in 1.18.2

### ISSUE THREAD

**Issue by SimplyHansel** [wendall911/TinkerSurvival#59]
exactly as the title says.  no matter what stone surface i use, I cannot turn flint into shards.  i tried disabling all my other mods.  I tried changing the config to make it a 100% chance of getting a shard.  nothing Ive tried has worked.

**Comment by wendall911** [comment]
There is a book. Two dirt. Take a look. The mod changed in 1.18.2. I t is also in the written description that it changed. 


I assume you only watched the 1.12.2 video? Please let me know if that is the case, because I think I'm going to remove it.

**Comment by wendall911** [comment]
Closing this assuming this is for 1.18. I'm removing the video today to not confuse folks.

**Comment by SimplyHansel** [comment]
oh gosh im so sprry i didnt see the email.  yes it was for 1.18.2 .  sorry
it wasnt actually an issue.  i just could not the life of me figure it
out.  thank you for being so diligent with this
