### ISSUE TITLE
add the ability to disable the tool usage removal feature

### ISSUE THREAD

**Issue by TheNimbleNinja** [wendall911/TinkerSurvival#60]
i am wanting to use this mod for everything but the tool remove feature and i tried whitelisting mods and it didnt work mostly, also your discord link is broken

**Comment by wendall911** [comment]
I'm never going to do that, it entirely defeats the purpose of the mod, which is Tinkers' Construct immersion. I'm going to close this, please use something else. Without that feature, the mod isn't much. If you just want an alternative method for cutting wood, there are other mods that do this. Other features can be found elsewhere.
