### ISSUE TITLE
Repairing damaged Crude Knives duplicates them

### ISSUE THREAD

**Issue by WesternFreak** [wendall911/TinkerSurvival#61]
When trying to vanilla-repair flint knives (as in, crafting 2 damaged tools in the crafting table) they output duplicates while keeping damaged ones in the crafting table (instead of "merging" them into a single one, as expected).
![2022-06-09_17 06 18](https://user-images.githubusercontent.com/4205706/172894349-bbb97595-f462-4747-ac3e-c7131fe7c534.png)
![2022-06-09_17 06 22](https://user-images.githubusercontent.com/4205706/172894357-b48240e6-c7f9-42f5-8109-27d239083a86.png)
![2022-06-09_17 06 29](https://user-images.githubusercontent.com/4205706/172894358-ee2d06e2-a1c0-458e-9810-a0639ecb0bf1.png)

This process can be repeated with the excess knives to create even more, obviously:
![2022-06-09_17 09 54](https://user-images.githubusercontent.com/4205706/172894360-c0a15d24-ee16-47f0-9c7b-f3fd1d816f96.png)

This also appeared to be an issue with damaged Crude Saws too (didn't experiment with anything else).

Minecraft 1.18.2
Forge 40.1.16
Tinker's Survival 2.2.4.0
Tinker's Construct 3.5.0.17
Mantle 1.9.20
(and JEI 9.7.0.196)

**Comment by wendall911** [comment]
Oh, good catch. I don't even remember adding this as a recipe, lol.

**Comment by wendall911** [comment]
Ok, I need to set everything to not repairable. Not enough information comes back to actually make this work. It isn't a really good implementation on the Forge side of things. :(
