### ISSUE TITLE
"ENABLE_ROCK_GEN= false" config from "defaultconfigs" folder fails to prevent rock pile world gen

### ISSUE THREAD

**Issue by WesternFreak** [wendall911/TinkerSurvival#62]
A world with the config of rock piles' world gen disabled still generates them on the world's surface.

You should be able to replicate with the following:
- generate a new world on a fresh game (as in, no modifications made to the configs on any mod)
- copy the default generated "tinkersurvival-server.toml" file in the "serverconfig" folder
- paste it in the "defaultconfigs" folder
- modify the ENABLE_ROCK_GEN config to "false"
- generate a second world
- even though the generated "tinkersurvival-server.toml" file in the "serverconfig" folder of the second world respects the "false" setting from the "defaultconfigs" the rock piles are still being generated

Minecraft 1.18.2
Forge 40.1.16
Tinker's Survival 2.2.4.0
Tinker's Construct 3.5.0.17
Mantle 1.9.20
(and JEI 9.7.0.196)

**Comment by wendall911** [comment]
Thanks for reporting. I may have not implemented this feature from 1.12 to be honest. I fail to see why anyone would possibly use the mod without it. Anyhow, would like to get some feedback about how? So confused. This mod literally adds about half a day of early game play and forces proper tool use. So very confused. I can't even remember why this was an option to begin with to be honest.

I've been away from my computer for a few days sick. When I feel better (hopefully soon) I will take a look and can implement. Would like to know if this is needed, or just reporting it as broken?

**Comment by WesternFreak** [comment]
Thank you for you reply, especially in your current circumstances, I'll take the chance to wish you a get well soon.

>Anyhow, would like to get some feedback about how? 

Of course: as I understand it the rocks have a major use to players that might not have easy access to gravel (as #34 pointed out) but they don't really have a purpose later on when the player is established and has proper tools and cobblestone available and I consider it somewhat clutter to the world's surface.
My personal modpack uses Terraforged for world generation, which _usually_ spawns the player right next to a river with patches of gravel, rendering the stone route worthless.
Please don't get me wrong, I really like this mod **especially** when it comes to forcing proper tool usage (slow down when using improper tools and whitelisting tools), but I found myself using KubeJS to tweak the early game with some custom recipes (in the case of Tinker's Survival, to avoid using Rock in the Hatchet recipe in favour of Flint).

To be clear regarding your final question
>Would like to know if this is needed, or just reporting it as broken?

If you decide the mod should feature the rock piles on the world's surface, so be it, it is your mod after all and it is not a game breaking issue to me :) but since it's a configuration setting it should probably EITHER work accordingly (with the Crude Hatchet/Mortar and Pestle made with a piece of Flint as an alternate recipe to Rock, so the rocks are not strictly necessary?) OR be removed to prevent any confusion to some other player.

EDIT:
the JEI information tab still points out to usage of flint to get shards, which is no longer the case too
![image](https://user-images.githubusercontent.com/4205706/173185195-155f48da-3969-42a8-9097-196d2707a495.png)

**Comment by wendall911** [comment]
Ok, thank you so much for the feedback, my brain has been so foggy I should have probably remembered this use-case!

And yes, I totally understood about the unnecessary clutter. I need to also make sure to update the message in JEI to reflect the settings. I'll work on this soon. Still not quite feeling better, but hoping later today I can push out a fix. Appreciate the feedback, very, very helpful!

**Comment by wendall911** [comment]
Ok, I just took a look today and confirm what you're saying. I know this worked at some point. The code is implemented correctly. This actually looks like a Forge bug. The configs are loading after a few key worldgen events are fired (like the biome loading event) that are responsible for worldgen features. I'm going to dig deeper and see if there is a bug reported already for this, or if there is potentially a workaround I can implement.

**Comment by wendall911** [comment]
Ok, I can fix this. The issue you're going to have, and I apologize that this isn't updated in the 1.18 update description. But it isn't possible to "knapp" flint in the current version, only the stones you find. So if you disable it, there is no way to make crude tools at all, as flint shards are required. I"m not certain making the mod unplayable is really what you want, but maybe there is a way you can make it work through a crafttweaker script or something.

I'll also update the description in JEI for knapping, thanks for letting me know about that.

**Comment by wendall911** [comment]
Ok, a new version has been published with the fix. You'll have to edit the tinkersurvival-common.toml file which is where the settings for the worldgen feature will live now. It will successfully apply to all newly generated worlds.
