### ISSUE TITLE
[Bug] Individual tool whitelist does not work

### ISSUE THREAD

**Issue by breadguyyy** [wendall911/TinkerSurvival#63]
None of the tools I listed in the tool whitelist are actually whitelisted

Here's the relevant server config lines (in case I'm being stupid):

`#List of individual tools that will always work. Format tooltype-modid:item Default: ["hammer-immersiveengineering:hammer", "wirecutter-immersiveengineering:wirecutter"]
items = ["hammer-immersiveengineering:hammer", "wirecutter-immersiveengineering:wirecutter", "sword-twilightforest:ice_sword", "sword-twilightforest:glass_sword", "pickaxe-twilightforest:giant_pickaxe", "sword-twilightforest:giant_sword", "axe-twilightforest:gold_minotaur_axe", "axe-twilightforest:diamond_minotaur_axe", "pickaxe-twilightforest:mazebreaker_pickaxe", "hammer-oreganized:bush_hammer", "hammer-mcwwindows:hammer"]
`

**Comment by wendall911** [comment]
Sorry, I've been out for a bit with an illness. I will take a look at this soon. Appreciate the report.
