### ISSUE TITLE
[Suggestion 1.18] Disable vanilla armor

### ISSUE THREAD

**Issue by Insane96** [wendall911/TinkerSurvival#66]
Since TiCon 3 has armor, would be good to have a way to prevent vanilla armor from working.
As I can see there's a ARMOR_FAIL sound that's never used. Probably from previous version.

**Comment by wendall911** [comment]
I'm working on a modpack release today. I'll probably add an option for this soon. It will be disabled by default, as I'm not fully happy with the TCon armor as compared to Constructs' Armory.
