### ISSUE TITLE
Harvest Crash

### ISSUE THREAD

**Issue by Fortist** [wendall911/TinkerSurvival#7]
Harvested a stone on the ground after starting a new game and got this
https://pastebin.com/gedYGfsj

**Comment by wendall911** [comment]
Thanks for the report. Not sure the cause. The crash doesn't make any sense, it looks more like an OOM (Out of Memory) thing. No way to get an exception like this unless the variable is suddenly unloaded. That probably only happens with memory corruption or out of memory error.

Is it reproducible in your pack? Try increasing the available memory and see if it happens. Let me know as this isn't a code issue.

**Comment by wendall911** [comment]
I reproduced it, so will get a fix out. Sorry about this!
