### ISSUE TITLE
Texture-less tools with rubidium 1.18.2

### ISSUE THREAD

**Issue by yeahpng** [wendall911/TinkerSurvival#72]
Tools from this mod look completely white when rubidium (sodium port for forge) is installed alongside it. This used to be a problem with base tinkers but it has since been fixed.

**Comment by wendall911** [comment]
Ok, thanks for the report. I didn't realize it had been fixed in TCon. I'll look into it and get this fixed. Thanks for the report.

**Comment by wendall911** [comment]
The issue isn't resolved in TCon, if it is working, it is only incidental. This looks to be a Rubidium bug. https://github.com/SlimeKnights/TinkersConstruct/issues/4922

**Comment by wendall911** [comment]
That said, I am going to mess around with settings and see if I can get this working. The textures are generated correctly, so I'm not sure exactly what the issue is.

**Comment by wendall911** [comment]
Ok, I figured out the issue. Going to push another release to address this.
