### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by CaptainSoulo** [wendall911/TinkerSurvival#74]
When attempting to use bone meal on grass blocks, the game will immediately crash and come up with this error.

On the surface it doesn't blame any mods but the following line is the second line to come up in the stack trace. I was wondering if it's something to do with Tinker's Survival.

tinkersurvival.event.HoeEventHandler.onHoeBlock(HoeEventHandler.java:27) ~[TinkerSurvival-1.18.2-2.2.4.2.jar%23341!/:task ':jar' property 'archiveVersion'] {re:classloading}

[crash-2022-06-30_09.21.39-client.txt](https://github.com/wendall911/TinkerSurvival/files/9028660/crash-2022-06-30_09.21.39-client.txt)

**Comment by wendall911** [comment]
Ok, this likely not caused by this mod, but certainly is throwing an error. I can do some more checks in the code to ensure that there can't be a crash generated here. I'll update with a new release and let you know here.

**Comment by wendall911** [comment]
Something isn't firing correctly and player is returned as null. I just make it ignore this when it happens. I'm not sure what the issue might be, but having some safer code will at least allow it to ignore whatever the issue is.

Thanks for the report!

**Comment by wendall911** [comment]
Here is the latest update. Give this a try: https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/3855486
