### ISSUE TITLE
[1.18.2] String not dropping from Infested Leaves

### ISSUE THREAD

**Issue by Boomflex** [wendall911/TinkerSurvival#75]
Version: TinkerSurvival-1.18.2-2.3.2.2.jar
Forge: 40.1.68

String not dropping from infested leaves using wooden hoe, stone hoe or stone mattock even though the block breaks as per config.

https://streamable.com/4ac7wj

**Comment by wendall911** [comment]
I've not looked at Ex Nihilo integration before. Can you share your config, specifically what you added for support? I will take a look sometime today, but the config would be helpful.

**Comment by Boomflex** [comment]
Hi Wendall, thanks for the swift reply!

https://pastebin.com/usqxJdfc

Thats the tinkersurvival-server.toml

**Comment by wendall911** [comment]
Ok, this is really an issue in Ex Nihilo, as they didn't tag their leaves. I'll go ahead and add the tag. (although you could add this to datapack data as well). It isn't a big deal. I'll mess around with the config and make sure everything is working correctly. I'll post my config and an update on curseforge shortly.

**Comment by wendall911** [comment]
Ok, this is an issue with ExNihilo. I just tested without Tinkers' Survial, and nothing drops if you don't use the Crook. That said, there is an issue with the crook that I need to push out. As for the drops, you'll have to use a Crook unless they change the behavior of the infested leaves. It looks like this is the intended behavior.

**Comment by wendall911** [comment]
Also, just adding: "exnihilosequentia" to the mods list will be enough. As there is only the hammer and crook.

**Comment by wendall911** [comment]
Ok, I just pushed https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/3900686

That will at least allow ExNihilo to function with the crook. As for drops with a hoe, that's another issue for the integration. It appears to bee hard-coded as a crook recipe for drops.

**Comment by Boomflex** [comment]
Perfect, thanks for the fast work and insight!
Appreciate the help and I look forward to launching my Tinker Survival Skyblock-esque pack!

**Comment by wendall911** [comment]
Please let me know when you do. The designers for the mod play a lot. They
would love to play a skyblock modpack. I'll follow on github as well!

**Comment by Boomflex** [comment]
Ok, can you also add Tinkers Hammer to the pickaxe list.

Not able to crush cobble as it only allows picks.

https://streamable.com/fod5sy

**Comment by wendall911** [comment]
Done: https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/3904062

I should have probably had hammers in the list of pickaxe items already. Thanks for pointing it out.
