### ISSUE TITLE
Crafting recipes involving tinkersurvival tool tags crash the game when you try to craft them in a mechanical crafter

### ISSUE THREAD

**Issue by secretmeister** [wendall911/TinkerSurvival#76]
Whenever you try to craft a recipe where one of the ingredients is a tinkersurvival tagged item and you use a tinker tool rather than the crude one in a mechanical crafter, it crashes.
[crash-2022-08-02_11.12.53-server.txt](https://github.com/wendall911/TinkerSurvival/files/9245132/crash-2022-08-02_11.12.53-server.txt)

**Comment by wendall911** [comment]
Ok, this is a fairly simple fix. I just had a line in the wrong place. The thing is that I can't allow auto crafters, as there isn't any way to invalidate the recipe when the tool is broken. If you do end up using the tool, the tool will not survive.

I'll release a fix to curseforge now.
