### ISSUE TITLE
[Suggestion] Only allow "crafted" versions of tools to be useless

### ISSUE THREAD

**Issue by CaptainSoulo** [wendall911/TinkerSurvival#77]
Hi, I have a suggestion that might be a big ask but I figured I'd try anyway.

So the way I'm developing my current modpack is to goad people into using Tinker's Construct. As this mod does an excellent job at this, I also have users who'd like to use the enchantment system of Apotheosis. So my thoughts are that if it's possible to give the "useless debuff" to only items that are crafted but looted ones would be allowed to not have this debuff. Is this a possibility in anyway?

Even if it were a setting or even a tag where I can stamp it onto loot tables would be fantastic.

Thanks for your hard work on this mod! I absolutely love it!

**Comment by wendall911** [comment]
That's a pretty good idea. I don't think it would be bad to have a tag based whitelist option. I currently have this for blocks for folks to add things in data packs. I hadn't thought about custom tag for loot tables. I'll add it and post here when I have it in so you can test it. I don't have the level of control to do much outside of just checking a tag or the item/mod id, so you'd have to add a tag in the loot tables. 

Also, please share how you do this! I can add to the wiki.

**Comment by wendall911** [comment]
Ok, the latest release on Curseforge has this config option now:

#List of tags when added to tools or armor will always work.["whitelist_tools"]
tag = ["whitelist_tools"]

I just added whitelist_tools as an example, nothing is tagged with this.

https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/3918080
