### ISSUE TITLE
Crude saw is considered an axe, while normal saws are not

### ISSUE THREAD

**Issue by secretmeister** [wendall911/TinkerSurvival#78]
Crude saws work as axes, are effective on trees, can strip logs, can receive any axe enchantment, while compound tinkers saws cannot.

**Comment by wendall911** [comment]
Yep, that's by design. I could do some custom tool class, but that's the way it works for now. Is this an issue?

**Comment by secretmeister** [comment]
It is kind of, because there is then no point to the crude hatchet, as the saw can both cut down trees and turn them into planks

**Comment by wendall911** [comment]
Released this change on curseforge here; https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/3926803
