### ISSUE TITLE
[1.18.2] Item whitelist not working

### ISSUE THREAD

**Issue by serialtasted** [wendall911/TinkerSurvival#82]
So I'm adding items to the list of tools that should always work but none is working. All tools keep saying that they are for crafting usage only.

Here's my config file:

> #Chance for a successful flint knapping. (1.0 = 100%, 0.4 = 40%, etc.)
> #Range: 0.1 ~ 1.0
> FLINT_CHANCE = 0.6
> #Heal rate for bandages. Crude bandages are 50% less effective. (1.0 = 100%, 0.4 = 40%, etc.)
> #Range: 0.1 ~ 1.0
> HEAL_RATE = 0.14
> #Option to adjust slow down on wrong tool usage. (1.0 = 100%, 2.0 = 200%, etc.)
> #Range: 1.0 ~ 5.0
> SLOW_DOWN_MULTIPLIER = 2.0
> #List of mods that tools will always work for. All other mod tools will become wet noodles. Default: ["tconstruct", "tinkersurvival"]
> mods = ["tconstruct", "tinkersurvival", "create", "immersiveengineering", "framedblocks", "mcwroofs", "mcwwindows", "mcwbridges"]
> #List of individual tools that will always work. Format tooltype-modid:item Default: ["hammer-immersiveengineering:hammer", "wirecutter-immersiveengineering:wirecutter"]
> items = ["shears-minecraft:shears", "shears-botania:manasteel_shears", "shears-botania:elementium_shears"]
> #Used to dump log info for Tinkers's Survival Modpack. Ignore.
> LOG_MODPACK_DATA = false
> #List of mods that have blocks that are generally decorative in nature and require no tool for harvesting blocks. Default: ["cfm", "furnish"]
> blockmods = ["cfm", "furnish"]
> #Hunger penalty feature. If after dying, player is rewarded with reduced hunger levels.
> ENABLE_HUNGER_PENALTY = false
> #Hunger value after death in half shanks. (0 = Really? That's just cruel, 20 = No penalty.)
> #Range: 0 ~ 20
> HUNGER = 8
> #Saturation value after death. Range 0 to 20.
> #Range: 0 ~ 20
> SATURATION = 0
> #Health penalty feature. If after dying, player is rewarded with reduced health levels.
> ENABLE_HEALTH_PENALTY = false
> #Health value after death in half hearts.
> #Range: 0.5 ~ 100.0
> HEALTH = 6.0
> #The amount of generic damage in half hearts a non-whitelisted tool, or bare hand should do. Default 0
> #Range: 0 ~ 4
> GENERIC_DAMAGE = 0
> #Enforce use of armor whitelist. All other armor will not be equipable.
> ENFORCE_WHITELIST_ARMOR = false
> #List of mods that armor will be equipable for. Must enable ENFORCE_WHITELIST_ARMOR to be effective. Default: ["immersiveengineering", "tconstruct"]
> armormods = ["immersiveengineering", "tconstruct"]
> #List of individual armor items that will always work. Format modid:item Default: ["tconstruct:piggybackpack"]
> armor = ["tconstruct:piggybackpack"]
> #List of tags when added to tools or armor will always work.["whitelist_tools"]
> tag = ["whitelist_tools"]

Am I doing something wrong?

**Comment by wendall911** [comment]
I assume this is an issue with:
items = ["shears-minecraft:shears", "shears-botania:manasteel_shears", "shears-botania:elementium_shears"]

**Comment by serialtasted** [comment]
Most likely.. but what? I followed the instructions. Do you see anything misplaced?

**Comment by wendall911** [comment]
I'm just trying to clarify what problem you're having. Just dumping the config and having me guess isn't helpful. I'm asking, is the items array the issue?

**Comment by serialtasted** [comment]
I could just placed that line also. I know what the config does and have read the wiki. I don't get any errors or whatsoever. I've confirmed that the tag for shears is that and even deleted the config file, generated a new one and tried again to no avail. The reason I placed the whole config file was to see if I was doing something wrong on other line that I was missing somehow.

Right now I have no idea what might be the issue beside that's what I have in my config and it's not doing anything in-game to the tools in the config. The mods array is working fine

**Comment by wendall911** [comment]
Ok, let me take a look and see what is going on. I'll test and get back to you on this. Thanks for reporting.

**Comment by wendall911** [comment]
These settings work just fine for me. Unfortunately however, I am using the server configs with Forge and it is a mess. I'd recommend either 1. Add the config to defaultconfigs before generating a new world OR 2. Generate a world. Shut down the game, modify config and start game again

This is because Forge isn't handling server configs well for some reason. If it is in the defaults it works fine.

BTW, I loaded the exact config and everything works as expected.

**Comment by serialtasted** [comment]
Sorry for the delay on my response.
I tried what you suggested and checked if the config file matched inside the save file but it still doesn't work. I really have no idea what is going on here. Do you know of any incompatibility of some sort with other mods? Or something that other mods might do that cancel out the whitelisting of items?
It's weird because the mod is working and is dummying the tools but it's ignoring the whitelist for some reason

**Comment by wendall911** [comment]
I'm closing this as stale. I hope the issue got sorted. There cannot be a mod conflict, and the config you've shared works. Unless there is a specific mod that isn't working. If that is the case, double check the modid.
