### ISSUE TITLE
[1.12.2] Mod blocks whitelist in 1.12.2 isn't working

### ISSUE THREAD

**Issue by JadianRadiator** [wendall911/TinkerSurvival#86]
Mod blocks whitelist in 1.12.2 isn't working.
I've tried everything along the lines of the following
mod:block
\<mod:block\>
mod:block:meta
\<mod:block:meta\>

**Comment by NotTohm** [comment]
same for me its been a year bruh why hasnt anyone responded

**Comment by JadianRadiator** [comment]
It's feature you said it has.
And on top of that it's in the config file.
So why the lie that it isn't planned?

**Comment by wendall911** [comment]
1.12.2 is many years old and no longer supported. Please don't respond to this issue again. It isn't a lie, you are just being entitled. Go away.
