### ISSUE TITLE
"items = []" config from "defaultconfigs" folder fails to always work. 

### ISSUE THREAD

**Issue by Tki-sor** [wendall911/TinkerSurvival#87]
You should be able to replicate with the following:

    generate a new world on a fresh game (as in, no modifications made to the configs on any mod).

    copy the default generated "tinkersurvival-server.toml" file in the "serverconfig" folder

    paste it in the "defaultconfigs" folder.

    modify the item=[] config to:
    ["hammer-immersiveengineering:hammer", "wirecutter-immersiveengineering:wirecutter", "pickaxe-botania:manasteel_pick", "trident-minecraft:trident", "sword-minecraft:wooden_sword", "shovel-minecraft:wooden_shovel", "pickaxe-minecraft:wooden_pickaxe", "axe-minecraft:wooden_axe", "hoe-minecraft:wooden_hoe", "sword-minecraft:stone_sword", "shovel-minecraft:stone_shovel", "pickaxe-minecraft:stone_pickaxe", "axe-minecraft:stone_axe", "pickaxe-minecraft:iron_pickaxe", "shovel-minecraft:iron_shovel", "sword-minecraft:iron_sword", "hoe-minecraft:golden_hoe", "axe-minecraft:golden_axe", "shovel-minecraft:golden_shovel", "pickaxe-minecraft:golden_pickaxe", "sword-minecraft:golden_sword", "hoe-minecraft:stone_hoe", "axe-minecraft:iron_axe", "hoe-minecraft:iron_hoe", "sword-minecraft:diamond_sword", "shovel-minecraft:diamond_shovel", "pickaxe-minecraft:diamond_pickaxe", "axe-minecraft:diamond_axe", "hoe-minecraft:diamond_hoe", "sword-minecraft:netherite_sword", "shovel-minecraft:netherite_shovel", "hoe-minecraft:netherite_hoe", "axe-minecraft:netherite_axe", "pickaxe-minecraft:netherite_pickaxe"]

    generate a second world

![2022-12-15_15 21 18](https://user-images.githubusercontent.com/78548154/207797867-9b4ab4eb-03fb-450c-bf6f-6fbdb2b43eec.png)

Minecraft 1.18.2
Forge 40.1.86
Tinker's Survival 2.3.10.2
Tinker's Construct 3.5.2.40
Mantle 1.9.31

**Comment by JadianRadiator** [comment]
Default configs only copy over when you create new saves.
They don't copy over when loading a already existing save.
