### ISSUE TITLE
Tinkers ToolPart Swaping - Dupes Final Product

### ISSUE THREAD

**Issue by ACrazyD** [wendall911/TinkerSurvival#88]
Forge: 40.1.93 for 1.18.2
Mod Version: 2.3.10.2
Tinkers Version: 3.5.3.63 (Release Version, Just noticed a Beta Version)
Other Tinkers Addons: "Tinkers Integrations And Tweaks by wendall911" and "Tinkers leveling Addon By Pyre540"
Modpack: SkyMachina (A Custom Modpack made by me)

Info:
When testing i tested with a TS Saw. If you try to swap a part on a damaged tool, it will allow you to not only swap the tool part. But also leaves the items in the tool station. allowing you to leave the station and reenter it and pull the same item out again and again.

Relogging does not affect this either..  And Damaged or fully Repaired does not appear to affect it.

**Comment by wendall911** [comment]
Ok, I thought this was fixed. I'll retest and get a fix out.

**Comment by wendall911** [comment]
Fixed in latest release 2.3.10.5. Fixed in #91
