### ISSUE TITLE
Plant Fiber JEI Description

### ISSUE THREAD

**Issue by NielsPilgaard** [wendall911/TinkerSurvival#9]
Hey o/ The Plant Fiber JEI description is a bit off. It calls Plant Fiber "Grass fibers", says it only drops from tall grass, and is used to make "Grass String".

**Comment by wendall911** [comment]
Hey, thanks for the report. I have a couple other small things I need to fix today as well. :+1:

**Comment by NielsPilgaard** [comment]
Damn that was fast, thank you!
