### ISSUE TITLE
[1.18.2] Repairing or Part Swapping a Knife or Saw Duplicates Them.

### ISSUE THREAD

**Issue by ShiftySnowWolf** [wendall911/TinkerSurvival#91]
When repairing a saw or a knife, exit the tinker's station and reopen the tinker's station, the damaged tool or unmodified tool and new part reappears allowing you to create an infinite amount of Tinker's Survival tools. This allows you to melt down  or deconstruct duplicated tools for an infinite supply of resources. Another related issue, the tinkers station does not make a sound when performing either of these tasks with Tinker's Survival tools.

**Comment by wendall911** [comment]
I will retest this. I would have sworn that this was fixed in the latest version.

**Comment by nivthefox** [comment]
Just tested this on the latest version and am having the same issue.

**Comment by poly-1810** [comment]
yep, same here, a modlist would probably be good to hand tho

**Comment by Alarak-Alex** [comment]
The same issue may occur with the latest version.

**Comment by wendall911** [comment]
Ok, this is a TCon issue that I need to apply another workaround for. I will update when I have this fixed.

**Comment by wendall911** [comment]
Fix pushed for latest release 2.3.10.5
