### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by poly-1810** [wendall911/TinkerSurvival#97]
the mod appears to crash on startup, most recent curseforge version
[latest.log](https://github.com/wendall911/TinkerSurvival/files/11639526/latest.log)
[crash-2023-06-02_17.22.27-fml.txt](https://github.com/wendall911/TinkerSurvival/files/11639528/crash-2023-06-02_17.22.27-fml.txt)

**Comment by poly-1810** [comment]
just wanted to let you know early, so that it can hopefully be fixed soon

**Comment by wendall911** [comment]
This is odd, I think something went wrong with the upload. I did a patch version bump an re-uploaded. I'll test with the file now and respond here.

**Comment by wendall911** [comment]
Ok, latest version now works. Thanks for the report. I think it didn't build correctly for some reason. I've not seen this issue before. Version 2.3.10.4 is working https://legacy.curseforge.com/minecraft/mc-mods/tinkersurvival/files/4568914
