### ISSUE TITLE
[1.18.2]Please adding more options in the confing files

### ISSUE THREAD

**Issue by ShootRK** [wendall911/TinkerSurvival#98]
There used to be more options in the file at 1.12, but at 1.18 they fade away.
Please adding the options in 1.12 to 1.18

**Comment by wendall911** [comment]
Most of the settings are still there, you have to check the server configs. Those can be found in the world save folder -> serverconfig folder. File is called tinkersurvival-server.toml

A few settings (mostly for drop rates and recipes) moved to using datapacks, as Tinkers' Construct has done the same. If you want an example of how the datapack overrides are done, the official modpack is a good example. https://www.curseforge.com/minecraft/modpacks/tinkers-survival-official

**Comment by ShootRK** [comment]
Thank YOU
