### ISSUE TITLE
[Bug] Tinker's Survival version 2.3.10.4 for 1.18.2 triggers on leaves

### ISSUE THREAD

**Issue by JadianRadiator** [wendall911/TinkerSurvival#99]
[Tinker's Survival version 2.3.10.4 for 1.18.2](https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/4568914) is triggering on leaves.
The previous version ([Tinker's Survival 2.3.10.2 for 1.18.2](https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/4027778)) does not.
2.3.10.4 is unplayable because of this.

**Comment by wendall911** [comment]
There are very minor differences between these versions. I only updated some of the rendered png files in the datapack. I will do some testing though.

**Comment by wendall911** [comment]
I am not seeing this issue. Plant fiber is dropping normally as well.

**Comment by JadianRadiator** [comment]
I said it was blocking breaking leaves.
I could re-download that version to see if it's exclusively leaves.
But that's assuming sticks can drop from more than just leaves.
If you can't get leaves from anywhere else, it's unplayable.

**Comment by wendall911** [comment]
There is nothing changed in the block breaking mechanic outside of the correct tool enforcement. Can I get a little more information on this? Nothing changed between versions.

**Comment by wendall911** [comment]
I can punch leaves and break them. I can use shears as well to get leaves. Maybe there is a specific mod leaves that are problematic?

**Comment by JadianRadiator** [comment]
Well in that case it would be the Dynamic Trees mod.
But I still don't see why downgrading the version of Tinker's Survival used and _only_ Tinker's Survival would correct the interaction issue.
And Tinker's Survival was the only mod I switched between it failing and getting it to work.

I can't just boot it back up as the setup was on a cloud pc, and they had to wipe its storage when I upgraded it.

**Comment by wendall911** [comment]
Yeah, I don't think it works correctly with Dynamic Trees unless it is whitelisted. I haven't tested in a while, as I didn't realize they finally updated for 1.18.2. Let me know if you find anything else out, I'll continue to test on my end.

**Comment by JadianRadiator** [comment]
The old version of Tinker's Survival, as well as versions older than that
work just fine.
It's specifically the newer version of Tinker's Survival I mentioned that
isn't working with it.
